import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { CartProvider } from "./context/CartContext";
import Header from "./header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col">
        <Header />
        <main className="flex-grow">
          <CartProvider>{children}</CartProvider>
        </main>
        <footer className="bg-pink-600 text-white p-2">
          <div className="font-semibold">
            <p>© {new Date().getFullYear()} Sakal Shop</p>
            <div className="flex gap-4">
              <a>Instagram</a>
              <a>Whatsapp</a>
              <a>X</a>
              <a>Phone: +91 9743583474</a>
            </div>
          </div>
        </footer>
      </body>
    </html>
  );
}
